options:
  config:
    type: string
    default: ''
    description: |-
      The configuration that will be used by the JMX exporter
      visit https://github.com/prometheus/jmx_exporter/tree/master/example_configs.

      The configuration is rendered by Jinja2, which offers the following variables
      - juju_application_name
      - juju_unit_name
